version: '3.8'

services:
  bot:
    container_name: bot
    build: .
    env_file:
      - .env
    ports:
      - '3000:${PORT}'
    command: node index.js
    depends_on:
      - db
    networks:
      - app-network
    restart: always

networks:
  app-network:
    external: true

volumes:
  db_data: